### ISSUE TITLE
Ideas for v4 API

### ISSUE THREAD

**Issue by kagikn** [crosire/scripthookvdotnet#1227]
Since v3.7.0 is coming soon, which contains various performance improvements, compatibility fixes for earlier game versions and a lot of features, it's definitely a good idea we should start thinking how we should design the v4 API. We could provide more organized/polished APIs before I start thinking about how to create another runtime variant of SHVDN built against .NET 7+ with the use of features only available in .NET Core environment, such as `Span`.

More ideas will be suggested periodically, so it would be great if you could leave your own idea/feedback below.

# Struct InputArgument
One of our biggest design mistakes IMO. No need to use class for a single 8 byte value. For `OutputArgument`, we could define a implicit operator to convert to `InputArgument`. We don't want to push the GC pressure for native calls in future APIs.

# Weapon Classes Restructure 
We could make brand new weapon or ped inventory classes such as `PedInventory`, `PedWeaponInventory`, `PedWeaponInventoryItem`, `PedAmmoInventory`, and `PedAmmoInventoryItem`. There is `CWeapon`, which manages weapon states such as the current ammo count in clip (not a subclass of `CObject` btw), so we should not reserve `Weapon` class for the class for weapon inventory item of a ped IMO.

# Remove Auto Model Loading from Methods For Entity Creation
Looks like the not a few script developers casually create entities just with `World.Create*` (not applies to `CreateRandom` variants as they use one of loaded ambient models), while you cannot control how you load models by those methods and it is not guaranteed you can create multiple entities with different models. Not a few script developers don't bother to mark models they requested as no longer needed to the game can free the resource for the models, either.

# Dedicated Static Control Class
Simple, the `Game` class is kinda bloated for control methods. Since the exe has the dedicated class `CControl`, making a dedicated class for Control would make sense.

# Sound ID Handle Class or Struct
Maybe too late to create the sound ID handle class or struct in v3 API, but we should do this in v4.

# Misc
- Don't force script developers to create duplicate native calls
`Vehicle.CreatePedOnSeat` and `Vehicle.CreateRandomPedOnSeat` throw `ArgumentException` is the seat is occupied, but that forces `Vehicle.IsSeatFree` to be called twice to guarantee the methods will not throw `ArgumentException` for the seat being occupied.
- Make ISpatial only have Position
Having rotation prevent the `NavMeshBlockingObject` from having `ISpatial`. The same case may happen in other classes that represents the game classes or structs.
- Rename the Enum Bone to PedBoneTag

# Tasks
- [ ] Made InputArgument struct instead of class for v4 API
- [ ] Restructure weapon classes for v4 API
- [ ] Remove Auto Model Loading from Methods For Entity Creation for v4 API
- [ ] Create Dedicated Control class for v4 API
- [ ] Create Sound ID Handle Class or Struct for v4 API

**Comment by kagikn** [comment]
Change the plan in our task scheduler. I realized a pitfall that comes with big performance overhead in .NET Framework. [FiveM Collective realized the built-in Task classes are too slow to casually use in the Mono that FiveM uses](https://github.com/thorium-cfx/mono_v2_get_started/tree/8e17a1be9006468ecbb120a1584d99d89ea2d02c). Peek the implementation of FiveM's mscorlib.dll to confirm, it has `ExecutionContext` whose implementation is largely shared with the mscorlib.dll of .NET Framework 4.8. That would mean the `Task` classes in Mono that FiveM uses suffers as much overhead as in .NET Framework 4.8.

**Comment by BoBoBaSs84** [comment]
Hi,

It would be cool to have a "native" support for abstractions. So that you can develop against interfaces instead against the concrete implementations. This would make things more testable. You know something like:

`
using GTA;

public interface ITimeProvider
{
	/// <summary>
	/// Gets or sets the current date and time in the <see cref="World"/>.
	/// </summary>
	DateTime Now { get; set; }

	/// <summary>
	/// Gets or sets the current time of day in the <see cref="World"/>.
	/// </summary>
	TimeSpan TimeOfDay { get; set; }
}
`

`
using GTA;

internal sealed class TimeProvider : ITimeProvider
{
	public DateTime Now
	{
		get => World.CurrentDate;
		set => World.CurrentDate = value;
	}

	public TimeSpan TimeOfDay
	{
		get => World.CurrentTimeOfDay;
		set => World.CurrentTimeOfDay = value;
	}
}
`

With something like it you could use a test implementation to check for logic components that require the current in game date time or use a mock to test things.

`
Mock<ITimeProvider> mock = new();
mock.Setup(x => x.Now).Returns(DateTime.MinValue.AddYears(100));
mock.Setup(x => x.TimeOfDay).Returns(DateTime.MinValue.AddYears(100).TimeOfDay);
`

**Comment by kagikn** [comment]
I thought of nuget packages providing interfaces for abstraction for API layers, but I am speculating you'll end up dealing with versioning issues on interface implementation (such as old and new version resolution). However, maybe we shouldn't create many custom interfaces in API itself in the first place, since you would think of mocking typically when you use third party libraries IMO. I haven't used mocks much due to the nature of game modding where you can't exactly predict functions embedded in the game, but using your own mocks is a generally better option to me.

As for `PlayerProvider` you provided, it doesn't seem to me mock does a job for properties too good, since none of them doesn't execute complex logics afaik. `Game.Player.Character` only fetches local player index (always zero in SP) and gets the player ped handle (will have to register script entity index, but still not too complex). `Player.CanControlCharacter` basically reads/writes a value from/to a 4-byte value and that's it. `Player.IsDead` will only check if the player ped is not lower than the fatal injury threshold.

**Comment by kagikn** [comment]
Enabled GitHub Discussions for more potential engagement in discussions. crosire wouldn't enabled this, but I'm giving it a try. Discord server for SHVDN? I'll need more time to set up for that.

**Comment by kagikn** [comment]
> > Enabled GitHub Discussions for more potential engagement in discussions. crosire wouldn't have enabled this, but I'm giving it a try. Maybe we can spot design flaws more easily. Discord server for SHVDN? I'll need more time to set up for that.
> 
> @kagikn
> 
> Have you been able to move forward on Discord? ;)

Sorry, but not ready yet.
